[package]
name = "illuminate-contracts"
version = "0.1.0"
edition = "2024"
authors = ["joseph@raubstudios.com"]
description = "Illuminate Contracts"
license = "MIT"

[lints.rust]
dead_code = "allow"
unused = "allow"
